### ISSUE TITLE
[Issue] Sales and Listning Doesn't work

### ISSUE THREAD

**Issue by gunawan817** [lucid-eleven/nft-discord-bot#2]
Couldn't retrieve event

**Comment by lucid-eleven** [comment]
Apparently OpenSea made a change recently that made an API key mandatory for using their Events endpoint.  Have you got an API key?

**Comment by gunawan817** [comment]
I do not get it

**Comment by lucid-eleven** [comment]
Have you got an API key from OpenSea? https://docs.opensea.io/reference/request-an-api-key

It used to be optional, just rate limited, but they made a change in the past week to block people accessing the Events API without an API key, which is what the Sales and Listings use.
