### ISSUE TITLE
Too Many Requests

### ISSUE THREAD

**Issue by ecology99** [lucid-eleven/nft-discord-bot#3]
Hello,

I already have an API and everything works but I'm constantly getting this messages:

Error: Couldn't retrieve events: Too Many Requests
at Object.execute (/root/suk/tcbc/cronjobs/listing.js:37:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't retrieve events: Too Many Requests
    at Object.execute (/root/suk/tcbc/cronjobs/sales.js:37:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Anything I can do to fix this?
I also noticed the notifications are very delayed compared to bots running on other Discord Servers.

Thank you!

**Comment by lucid-eleven** [comment]
Hi, I set the bot to get updates every 30 seconds, it's possible to make a small adjustment to the code make it run more frequently.

I'm not sure about the too many requests error, sounds like OpenSea rate limiting their API.  But you're saying that the bot still works?

**Comment by ipmanlk** [comment]
This is not an issue with the bot. OpenSea API is rate limiting you.
